apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-server.name" . }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "api-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ include "api-server.name" . }}
    spec:
      serviceAccountName: {{ include "api-server.name" . }}
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: init-{{ .Chart.Name }}-migration
          image: "{{ .Values.image.migrationsName }}:{{ .Values.image.migrationsTag }}"
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/App.toml
              subPath: App.toml
      volumes:
        - name: config
          configMap:
            name: {{ include "api-server.name" . }}
